export const TraceAttrs = Object.freeze({
  REVIEW_RUN_ID: "review.run_id",
  PR_ID: "review.pr_id",
  PR_TITLE: "review.pr_title",
  REPO_ID: "review.repo_id",
  ORG_URL: "review.org_url",
  PROJECT: "review.project",
  FILE_PATH: "review.file_path",
  FILE_RISK_LEVEL: "review.file_risk_level",
  FILE_TEST_STATUS: "review.file_test_status",
  FINDING_SEVERITY: "review.finding_severity",
  FINDING_CATEGORY: "review.finding_category",
  FINDING_CONFIDENCE: "review.finding_confidence",
  FINDING_FINGERPRINT: "review.finding_fingerprint",
  THREAD_ACTION: "review.thread_action",
  ERROR_TYPE: "review.error_type",
  CONFIG_PATH: "review.config_path",
  MODEL_NAME: "review.model_name",
  ITERATION_CURRENT: "review.iteration_current",
  ITERATION_PREVIOUS: "review.iteration_previous",
});
